---
title: "Writing iSEE extensions"
author: Kevin Rue-Albrecht^[kevinrue67@gmail.com],Federico Marini^[marinif@uni-mainz.de], Charlotte Soneson^[charlottesoneson@gmail.com]
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Writing iSEE extensions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Writing iSEE extensions

Authors:
    Kevin Rue-Albrecht^[University of Oxford],
    Federico Marini^[Johannes Gutenberg-Universität Mainz],
    Charlotte Soneson^[Friedrich Miescher Institute for Biomedical Research].
    <br/>
Last modified: 09 July, 2024.

## Overview

### Description

This package demo will present a brief introduction to the functionality of the
iSEE package and its existing extension packages, before demonstrating the
writing of new functionality suitable for release in additional extension
packages.

### Pre-requisites

Workshop prerequisites:

* Familiarity with the SummarizedExperiment class.
* Familiarity with the shiny package

Relevant background reading:

* EuroBioC2023:
  (
  [workshop](https://isee.github.io/iSEEDemoEuroBioC2023/articles/iSEEdemo.html)
  )
* EuroBioC2020: 
  (
  [workshop](https://isee.github.io/iSEEWorkshopEuroBioc2020/),
  [slides](https://isee.github.io/iSEEWorkshopEuroBioc2020Slides/)
  )
* BioC2020: 
  (
  [workshop](https://isee.github.io/iSEEWorkshop2020/),
  [slides](https://isee.github.io/iSEEWorkshop2020Slides/)
  )
* BioC2019
  (
  [workshop](https://isee.github.io/iSEEWorkshop2019/),
  [slides](https://isee.github.io/iSEEWorkshop2019Slides/)
  )
* Rue-Albrecht K, Marini F, Soneson C and Lun ATL. iSEE: Interactive SummarizedExperiment Explorer [version 1; peer review: 3 approved]. F1000Research 2018, 7:741 (https://doi.org/10.12688/f1000research.14966.1)

### Participation

Describe how students will be expected to participate in the workshop.

### _R_ / _Bioconductor_ packages used

List any _R_ / _Bioconductor_ packages that will be explicitly covered.

### Time outline

An example for a 45-minute workshop:

| Activity                     | Time |
|------------------------------|------|
| Packages                     | 15m  |
| Package Development          | 15m  |
| Contributing to Bioconductor | 5m   |
| Best Practices               | 10m  |

### Workshop goals and objectives

List "big picture" student-centered workshop goals and learning
objectives. Learning goals and objectives are related, but not the
same thing. These goals and objectives will help some people to decide
whether to attend the conference for training purposes, so please make
these as precise and accurate as possible.

*Learning goals* are high-level descriptions of what
participants will learn and be able to do after the workshop is
over. *Learning objectives*, on the other hand, describe in very
specific and measurable terms specific skills or knowledge
attained. The [Bloom's Taxonomy](#bloom) may be a useful framework
for defining and describing your goals and objectives, although there
are others.

### Learning goals

Some examples:

* describe how to...
* identify methods for...
* understand the difference between...

### Learning objectives

* analyze xyz data to produce...
* create xyz plots
* evaluate xyz data for artifacts

## Workshop

Divide the workshop into sections (`## A Section`). Include
fully-evaluated _R_ code chunks. Develop exercises and solutions, and
anticipate that your audience will walk through the code with you, or
work on the code idependently -- do not be too ambitious in the
material that you present.



